cmd_vel_mux:
  ros__parameters:
    subscribers:
      control_input:
        topic:       "/ctrl_vel"
        timeout:     0.1
        priority:    0
        short_desc:  "Input from control system"
      teleop_input:
        topic:       "/teleop_vel"
        timeout:     0.5
        priority:    1
        short_desc:  "Teleoperation input"
      safety_input:
        topic:       "/safety_vel"
        timeout:     0.25
        priority:    2
        short_desc:  "Safety controller input"
velocity_smoother:
  ros__parameters:
    frequency: 20.0
    feedback: 0
    speed_lim_v: 0.3
    speed_lim_w: 2.5
    accel_lim_v: 0.8
    accel_lim_w: 3.5
